### ISSUE TITLE
Add environment variable to toggle the hide video functionality

### ISSUE THREAD

**Issue by Createor** [TheConnMan/jukebot#142]
As a jukebot host I want to be able to configure whether that toggle is even available to users.

**Comment by TheConnMan** [comment]
What is the use case for this? Also, hide video is going to need to change anyways because of YouTube's ToS.

**Comment by Createor** [comment]
This would let the host decide whether they want to comply or not.

**Comment by TheConnMan** [comment]
Ah, ok. So removing "Hide Video" and replacing it with something compliant would cover this use case?

**Comment by Createor** [comment]
Correct
