### ISSUE TITLE
favoriting favorited but didn't post to chat or change the icon in the session

### ISSUE THREAD

**Issue by SirZach** [TheConnMan/jukebot#154]

**Comment by TheConnMan** [comment]
I believe this happens the first time a user favorites a video. Probably something with the favorites array being null, not empty when pulled from local storage.

**Comment by TheConnMan** [comment]
This got solved with #191, in particular defaulting the favorites array to `[]` in https://github.com/TheConnMan/jukebot/pull/191/files#diff-99db64bc2ad2d99ac4fc5e9fb1a0f73bR5.
