### ISSUE TITLE
Remove Song Message

### ISSUE THREAD

**Issue by TheConnMan** [TheConnMan/jukebot#172]
Should we have a "Remove Song" machine message? We have them for skipping and adding, but not removing.

**Comment by Createor** [comment]
I'm for it, though it could get a bit chatty when you're just rearranging upcoming songs

**Comment by TheConnMan** [comment]
Very true, though the readds do that anyways. Maybe it's time to just allow dragging/dropping of songs for reordering.

**Comment by Createor** [comment]
That's #65. I vote to promote this to an Improvement.
