### ISSUE TITLE
update page title to be <artist> - JukeBot

### ISSUE THREAD

**Issue by SirZach** [TheConnMan/jukebot#27]

**Comment by TheConnMan** [comment]
Do you mean the YouTube title or just the artist?

**Comment by SirZach** [comment]
youtube does `<artist> - Youtube` probably for brevity. you don't get a lot of room on those tab titles

**Comment by TheConnMan** [comment]
Implemented in b17a04dbf043462e1d61b714c2d1bc0bfc4b515e
