### ISSUE TITLE
Favoriting videos in the playlist dont' work

### ISSUE THREAD

**Issue by SirZach** [TheConnMan/jukebot#56]
Just sat and watched Jess try and favorite videos and nothing happened

**Comment by Createor** [comment]
I encountered a similar issue. The favoriting was actually happening for me, but the icons and favorites panel were not refreshed until the page was reloaded.

**Comment by SirZach** [comment]
@TheConnMan we might need to run a `$scope.$digest()` after favoriting

**Comment by TheConnMan** [comment]
There is no issue locally. Still digging in.

**Comment by TheConnMan** [comment]
This should be fixed with 81839e2502095fe5d3ce47b7952b0d5adde74910, but I can't reliably reproduce the issue to test.

**Comment by TheConnMan** [comment]
Verified to be fixed.
