### ISSUE TITLE
Show related videos (collapsable) 

### ISSUE THREAD

**Issue by jking13** [TheConnMan/jukebot#85]
It would be cool if we could display the current video's related video list. it would make genre/artist exploration easier.

**Comment by Createor** [comment]
I'd like just to see the video the app will play next if autoplay kicks in.

**Comment by SirZach** [comment]
@Createor i'm thinking of showing the top 5 related videos (at least). we have room for it.

**Comment by Createor** [comment]
I like the way it's semi-random. Reference the way giphy previews work in slack for what I think I'd like.

**Comment by SirZach** [comment]
Since giphy cycles through about 5 gifs when hitting next, not sure what the difference is

**Comment by jking13** [comment]
I think we could accomplish both if we highlighted the next video in autoplay inside of the related video list.
