### ISSUE TITLE
If list is empty we should auto play from favorites

### ISSUE THREAD

**Issue by jking13** [TheConnMan/jukebot#91]
We can randomly grab songs from the favorites of the current users.

**Comment by SirZach** [comment]
I really like the autoplay picking related videos to the last one just played. It's sort of a "let it ride" feature. Not sure this should be changed

**Comment by jking13** [comment]
maybe make it an option? it'd cool to have configurable auto play features

**Comment by swannysec** [comment]
Let it ride is good, leads to discovery of new music!  Though configurable options are always nice.

**Comment by TheConnMan** [comment]
Autoplay is good for filling in the gaps, but I often break open my favorites when there is a lull and add a bunch. I think that covers the use case without over-complicating it.
