### ISSUE TITLE
Different user privilages

### ISSUE THREAD

**Issue by jking13** [TheConnMan/jukebot#94]
user/mod/admin

**Comment by SirZach** [comment]
If someone wants to pay $ we can reopen

**Comment by jking13** [comment]
I kinda disagree with closing due to a feature being out of scope for the current activity of the project. It's entirely possible the project could grow significantly and have a lot of contributors, and if that happens it's reasonable to have more advanced features like this one.

I'd argue for letting the ticket stay in limbo.

**Comment by SirZach** [comment]
Keeping the issue open is distracting to what needs to be implemented.

**Comment by jking13** [comment]
this is why github needs to implement priorities on issues.
