### ISSUE TITLE
Move the search box and make it more prominent

### ISSUE THREAD

**Issue by jking13** [TheConnMan/jukebot#97]
As a new user the search box doesn't "pop" as much as it should. I think it would make sense to place it above the video list and to change the color or something to make it stand out more.

**Comment by SirZach** [comment]
Ideally I want it in the middle of the header akin to google music

**Comment by jking13** [comment]
That's fine. It's just difficult for a new user to instinctively find the main feature of the app. I like how google has a large search box and makes it a different color from the background. It would probably stand out much more if we did something similar.

**Comment by Createor** [comment]
![image](https://cloud.githubusercontent.com/assets/14128455/21251942/b3f121cc-c320-11e6-9f53-2141546b1d16.png)
Amazon music example, for those not using that service.

**Comment by Createor** [comment]
![image](https://cloud.githubusercontent.com/assets/14128455/21251959/dae679f8-c320-11e6-80ba-7f0f462ac400.png)

Google music for comparison

**Comment by jking13** [comment]
@Createor thanks for posting the comparison. I think that both options are more prominent than what is there now. Honestly there is next to nothing to draw a user's attention to the search box, which is something that I consider the core feature of the product.
