### ISSUE TITLE
Idle users

### ISSUE THREAD

**Issue by jking13** [TheConnMan/jukebot#99]
Mark a user as idle under certain conditions. This is useful to know if the room is "dead." Conditions could include no interaction with the app in a certain timeframe, not looking at the page for a while, etc.

**Comment by jking13** [comment]
Maybe the better answer is to have a settings page

**Comment by Createor** [comment]
I have to disagree that users should go "idle". I imagine a pretty common use case would be to let the tab play in the background while doing other work.

**Comment by jking13** [comment]
the way that I see it, is that the main selling point of the project is the user interaction. I could go on youtube or spotify if I wanted to listen to music by myself. I come to jukebox to talk shit about lady gaga costumes and share music I enjoy with friends.

**Comment by SirZach** [comment]
I defer to @TheConnMan as this app has already blown up way more than originally anticipated.

**Comment by jking13** [comment]
@SirZach 

`way more than originally anticipated.` 
- every open source project ever

**Comment by TheConnMan** [comment]
I'd say this could be a setting once room sizes get larger and contain more people who don't know each other. For now it's a lower priority though, there's enough indicators for us outside JukeBot (like Slack status) to indicate how active the room is.

BTW I have a ton of open source projects which are very much _not_ blowing up:
![image](https://cloud.githubusercontent.com/assets/1328448/21264629/22cc3ea2-c36b-11e6-872f-6e3f5b298ae8.png)

**Comment by Createor** [comment]
@TheConnMan, I'm a little disappointed that you do not also have a 'gatekeeper' project

**Comment by SirZach** [comment]
cool to close this? I completely agree with @Createor's point that it's a perfectly valid use-case to use jukebot in the background
